### ISSUE TITLE
POW Uncaught exception GET /slowota/image_user2-0x81000.bin

### ISSUE THREAD

**Issue by mr-blobby** [mirko/SonOTA#112]
- Operating System: 
Windows 10
- Python Version: 
sonota.exe
- Sonoff model: 
POW

I have successfully flashed a Basic and TH16 using the same setup.
The POW with "--legacy" and "--slowstream" parameters (according to the wiki), fails with an uncaught exception. The  tornado http server crashes when it tries to send slowota/image_user2-0x81000.bin

The full debug log is attached and this is the part where the exception happens:
```
2018-03-02 17:00:01,348: DEBUG: Slow Sending file: /slowota/image_user2-0x81000.bin (This may take several minutes)
2018-03-02 17:00:01,349: ERROR: Uncaught exception GET /slowota/image_user2-0x81000.bin?deviceid=100023e181&ts=553475508&sign=2e8b439e1758d825f3971abc70f6f91be7f2c6686aa06a6d8dc4d585656a6bb9 (10.0.0.106)
HTTPServerRequest(protocol='http', host='dl.itead.cn', method='GET', uri='/slowota/image_user2-0x81000.bin?deviceid=100023e181&ts=553475508&sign=2e8b439e1758d825f3971abc70f6f91be7f2c6686aa06a6d8dc4d585656a6bb9', version='HTTP/1.1', remote_ip='10.0.0.106', headers={'Host': 'dl.itead.cn', 'User-Agent': 'itead-device'})
Traceback (most recent call last):
  File "tornado\web.py", line 1511, in _execute
  File "tornado\gen.py", line 1055, in run
  File "tornado\concurrent.py", line 238, in result
  File "<string>", line 4, in raise_exc_info
  File "tornado\gen.py", line 307, in wrapper
  File "sonota.py", line 134, in get
FileNotFoundError: [Errno 2] No such file or directory: 'static\\image_user2-0x81000.bin'
2018-03-02 17:00:01,350: ERROR: 500 GET /slowota/image_user2-0x81000.bin?deviceid=100023e181&ts=553475508&sign=2e8b439e1758d825f3971abc70f6f91be7f2c6686aa06a6d8dc4d585656a6bb9 (10.0.0.106) 2.00ms
2018-03-02 17:00:01,355: DEBUG: << WEBSOCKET INPUT
2018-03-02 17:00:01,355: DEBUG: << {
2018-03-02 17:00:01,356: DEBUG:     "error": 404,
2018-03-02 17:00:01,356: DEBUG:     "apikey": "ff8b9401-bd51-496d-b2b2-b497cde26492",
2018-03-02 17:00:01,357: DEBUG:     "userAgent": "device",
2018-03-02 17:00:01,357: DEBUG:     "sequence": "1520006401332",
2018-03-02 17:00:01,357: DEBUG:     "deviceid": "100023e181"
2018-03-02 17:00:01,357: DEBUG: }
2018-03-02 17:00:01,358: DEBUG: ~~~ device acknowledged our action request (seq 1520006401332) with error code 404
2018-03-02 17:00:01,358: ERROR: *************************************************
2018-03-02 17:00:01,358: ERROR: Received a 404 error, try running with '--slowstream' option.
```

[debug_1520006351.log](https://github.com/mirko/SonOTA/files/1775826/debug_1520006351.log)

**Comment by mr-blobby** [comment]
Using Python 3.5.4 and the switches "--legacy" and "--slowstream", I managed to flash my Sonoff Pow without the issue I had with the executable of SonOTA.
