### ISSUE TITLE
Sonota.exe 2.6.0 close itself

### ISSUE THREAD

**Issue by blazkom** [mirko/SonOTA#161]
- Operating System: windows 10 64 bit
- Python Version: 3.7
- Sonoff model: basic
- Sonoff firmware version:  2.6.0 

When i start sonota.exe I input wifi and password of my home network. then i connect PC to wifi of sonoff but then sonota.exe close itself after 2-5 seconds. Maybe sonota.exe is not compatible with FW 2.6.0?

**Comment by Klangen82** [comment]
Same for me:/ Will never start the flash process or the sonata.exe will close itself.

**Comment by eloo** [comment]
For me the same. 
And i see the following output before it stops.
```
...Current IPs: ['10.10.7.2']
~~ Connection attempt
>> HTTP GET /10.10.7.1/device
<< {
    "deviceid": "****",
    "accept": "post",
    "apikey": "********"
}
>> HTTP POST /10.10.7.1/ap
>> {
    "serverName": "192.168.178.24",
    "password": "***************",
    "version": 4,
    "ssid": "***",
    "port": 8443
}
Traceback (most recent call last):
  File "sonota.py", line 734, in <module>
  File "sonota.py", line 729, in main
  File "sonota.py", line 612, in stage1
  File "httplib2\__init__.py", line 1322, in request
  File "httplib2\__init__.py", line 1072, in _request
  File "httplib2\__init__.py", line 1025, in _conn_request
  File "http\client.py", line 1198, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 576, in readinto
socket.timeout: timed out
[7380] Failed to execute script sonota
[7380] LOADER: OK.
[7380] LOADER: Cleaning up Python interpreter.
[7356] LOADER: Back to parent (RC: -1)
[7356] LOADER: Doing cleanup
[7356] LOADER: Freeing archive status for E:\Downloads\sonota.exe
```

any ideas?

**Comment by Klangen82** [comment]
I missed this:

![image](https://user-images.githubusercontent.com/25564168/50357648-f65b0f80-0556-11e9-81bc-236beffa193c.png)

So I guess this is a know issue...

**Comment by mgabor3141** [comment]
I'm getting the same error, but I'm only on 1.6.0; I would think that this version should still work.

Log:
```Using the following configuration:
        Server IP Address: 192.168.0.38
        WiFi SSID: mgnet_home
        WiFi Password: ******************
Platform: win32
** Now connect via WiFi to your Sonoff device.
** Please change into the ITEAD WiFi network (ITEAD-100001XXXX). The default password is 12345678.
To reset the Sonoff to defaults, press the button for 7 seconds and the light will start flashing rapidly.
** This application should be kept running and will wait until connected to the Sonoff...
.....................Current IPs: ['10.10.7.2']
~~ Connection attempt
>> HTTP GET /10.10.7.1/device
<< {
    "apikey": "e657c395-c1f5-43df-824a-f4f1fde041d2",
    "deviceid": "1000373102",
    "accept": "post"
}
>> HTTP POST /10.10.7.1/ap
>> {
    "port": 8443,
    "serverName": "192.168.0.38",
    "version": 4,
    "ssid": "mgnet_home",
    "password": "******************"
}
Traceback (most recent call last):
  File "sonota.py", line 734, in <module>
  File "sonota.py", line 729, in main
  File "sonota.py", line 612, in stage1
  File "httplib2\__init__.py", line 1322, in request
  File "httplib2\__init__.py", line 1072, in _request
  File "httplib2\__init__.py", line 1025, in _conn_request
  File "http\client.py", line 1198, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 258, in _read_status
  File "socket.py", line 576, in readinto
socket.timeout: timed out
[15064] Failed to execute script sonota
[15064] LOADER: OK.
[15064] LOADER: Cleaning up Python interpreter.
[11224] LOADER: Back to parent (RC: -1)
[11224] LOADER: Doing cleanup
```
