### ISSUE TITLE
Uncaught exception GET /slowota/image_user1-0x01000.bin

### ISSUE THREAD

**Issue by macemoneta** [mirko/SonOTA#62]
- Operating System: Linux (Fedora 26)
- Python Version: python3-3.6.3-2.fc26.x86_64
- Sonoff model: POW A16

Please also drag and drop the generated `debug_########.log` file onto the issue so it is attached.

Getting this error after downoad hits about 11%, after which the process cycles. Git clone is current as of today (2017-11-29).

Uncaught exception GET /slowota/image_user1-0x01000.bin?deviceid=10000bad60&ts=1270216262&sign=c90a2629e6dc1be372c6e49a3f3d55fd7cc61491eb617929eabe2a2d333ad67c (192.168.10.33)
HTTPServerRequest(protocol='http', host='dl.itead.cn', method='GET', uri='/slowota/image_user1-0x01000.bin?deviceid=10000bad60&ts=1270216262&sign=c90a2629e6dc1be372c6e49a3f3d55fd7cc61491eb617929eabe2a2d333ad67c', version='HTTP/1.1', remote_ip='192.168.10.33', headers={'Host': 'dl.itead.cn', 'Range': 'bytes=0-4095', 'User-Agent': 'itead-device'})
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/root/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/root/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/root/.local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "./sonota.py", line 155, in get
    yield self.flush()
  File "/root/.local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/root/.local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed
Cannot send error response after headers written
200 GET /slowota/image_user1-0x01000.bin?deviceid=10000bad60&ts=1270216262&sign=c90a2629e6dc1be372c6e49a3f3d55fd7cc61491eb617929eabe2a2d333ad67c (192.168.10.33) 35869.23ms

Debug log:

[debug_1511978395.log](https://github.com/mirko/SonOTA/files/1514961/debug_1511978395.log)

**Comment by macemoneta** [comment]
I found the problem. I noted reference to 192.168.10.33, when my (static) IP is 192.168.10.30. The IP address was 192.168.10.33 when I ran the pip3 install of the requirements. I uninstalled and re-installed the requirements and the install completed successfully.

pip3 uninstall  -r requirements.txt
pip3 install --user -r requirements.txt

Hopefully that helps someone else.
